### ISSUE TITLE
Pedestrian detection — OpenPose binary

### ISSUE THREAD

**Issue by mvondracek** [mvondracek/VUT-FIT-POVa-2018-Pedestrian-Tracking#17]
PR #16
Related: #6

**Comment by mvondracek** [comment]
With `OpenPoseBinaryDetector.detect_multiple_images` it is faster, great! 👍 
~~~
openpose_cpu_binary single image t=[14.223046313000001, 11.78526088, 14.576500374000002]
openpose_cpu_binary 10 images t=[84.91490911300001, 74.86650715100001, 70.52013804699999]
~~~

**Comment by mvondracek** [comment]
Is this task finished with 9f9a35afd8139ab2a4fd8d5a613451099d680944 and 3cee82e21fb06299cbc4f4e8c0bd5e2de6ecd64f?

**Comment by xstast24** [comment]
It is done.
![image](https://user-images.githubusercontent.com/9349888/50898307-102d9b00-140f-11e9-9843-718a62e2d731.png)
