### ISSUE TITLE
the openpose model

### ISSUE THREAD

**Issue by sry948749099** [mvondracek/VUT-FIT-POVa-2018-Pedestrian-Tracking#21]
Hi,

Could you provide the openpose model? i couldn't go to the website to download it.

Thanks

**Comment by xstast24** [comment]
Hi,
it should be available to download via official open pose scripts here https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/master/models (getModel.bat or getModel.sh in OpenPose github repository).
If it doesn't work for you, then please raise an issue in the openpose repository. Or download the precompiled CPU/GPU binaries https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases and try to use them.
